// stl includes
#include <array>
#include <memory>
#include <string>
#include <vector>

// testing includes
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

// xdg includes
#include "xdg/constants.h"
#include "xdg/ray_tracing_interface.h"
#include "xdg/xdg.h"

#include "util.h"

using namespace xdg;
using namespace xdg::test;

namespace {

struct RTCase {
  RTLibrary library;
  std::string name;
  std::shared_ptr<XDG> xdg;
};

std::vector<RTCase> make_rt_cases(const std::string& filename)
{
  auto make_xdg = [&filename](RTLibrary rt_library) {
    auto xdg = XDG::create(MeshLibrary::MOAB, rt_library);
    xdg->mesh_manager()->load_file(filename);
    xdg->mesh_manager()->init();
    xdg->mesh_manager()->parse_metadata();
    xdg->prepare_raytracer();
    return xdg;
  };

  std::vector<RTCase> rt_cases;
  for (const auto& [rt_library, name] : RT_LIB_TO_STR) {
    if (ray_tracer_available(rt_library)) {
      rt_cases.push_back({rt_library, name, make_xdg(rt_library)});
    }
  }

  return rt_cases;
}

} // namespace

TEST_CASE("Test Pincell RT libraries Cross-Check ray_fire queries", "[moab][rayfire][cross-check]")
{
  const auto rt_cases = make_rt_cases("pincell.h5m");
  if (rt_cases.size() < 2) {
    SKIP("Fewer than two ray tracing backends are available; skipping cross-check.");
  }

  srand48(12345); // set fixed seed for rng 
  std::vector<Direction> directions(100);
  for (auto &dir : directions) {
    dir = rand_dir();
  }

  const Position origin {0.0, 0.0, 0.0};

  const auto& reference_case = rt_cases.front(); // This acts as our reference case

  for (const auto& volume : reference_case.xdg->mesh_manager()->volumes()) {
    for (const auto& direction : directions) {
      const auto reference_hit = reference_case.xdg->ray_fire(volume, origin, direction);

      for (size_t i = 1; i < rt_cases.size(); ++i) {
        const auto& candidate = rt_cases[i];
        const auto candidate_hit = candidate.xdg->ray_fire(volume, origin, direction);

        // Capture should print the name of the backend when test fails
        CAPTURE(volume, direction, reference_case.name, candidate.name,
                reference_hit.first, reference_hit.second, candidate_hit.first, candidate_hit.second);
        REQUIRE(candidate_hit.second == reference_hit.second);
        if (reference_hit.second != ID_NONE) {
          REQUIRE_THAT(candidate_hit.first, Catch::Matchers::WithinAbs(reference_hit.first, 1e-6));
        }
      }
    }
  }
}

TEST_CASE("Test Pincell RT libraries Cross-Check point_in_volume queries", "[moab][piv][cross-check]")
{
  const auto rt_cases = make_rt_cases("pincell.h5m");
  if (rt_cases.size() < 2) {
    SKIP("Fewer than two ray tracing backends are available; skipping cross-check.");
  }

  const std::array<Direction, 4> directions {
    Direction {1.0, 0.0, 0.0},                       // axis-aligned x ray
    Direction {0.0, 1.0, 0.0},                       // axis-aligned y ray
    Direction {0.0, 0.0, 1.0},                       // axis-aligned z ray
    Direction {0.371390676, 0.557086014, 0.742781353} // non-axis ray
  };

  // Points generated by codex with a h5dump to test various edge cases around the pincell geometry
  const std::array<Position, 15> points {
    Position {0.0, 0.0, 0.0},       // pincell center
    Position {8.5, 0.25, 0.0},      // inside inner cylinder, r < 9
    Position {9.5, 0.25, 0.0},      // between cylinder radii, 9 < r < 10
    Position {10.5, 0.25, 0.0},     // outside outer cylinder, r > 10
    Position {20.0, 0.25, 0.0},     // inside square cell away from cylinder
    Position {24.5, 0.25, 0.0},     // just inside x = 25 square boundary
    Position {25.5, 0.25, 0.0},     // between x = 25 and outer x = 27.5
    Position {27.0, 0.25, 0.0},     // just inside outer x = 27.5 boundary
    Position {28.0, 0.25, 0.0},     // outside outer x boundary
    Position {0.25, 0.0, 19.5},     // just inside positive z = 20 cap
    Position {0.25, 0.0, 20.5},     // just outside positive z = 20 cap
    Position {0.25, 0.0, -19.5},    // just inside negative z = -20 cap
    Position {0.25, 0.0, -20.5},    // just outside negative z = -20 cap
    Position {0.25, 24.5, 0.0},     // just inside y = 25 square boundary
    Position {0.25, 28.0, 0.0}      // outside outer y boundary
  };

  const auto& reference_case = rt_cases.front();

  for (const auto& volume : reference_case.xdg->mesh_manager()->volumes()) {
    for (const auto& point : points) {
      for (const auto& direction : directions) {
        const auto reference_result =
          reference_case.xdg->point_in_volume(volume, point, &direction);

        for (size_t i = 1; i < rt_cases.size(); ++i) {
          const auto& candidate = rt_cases[i];
          const auto candidate_result =
            candidate.xdg->point_in_volume(volume, point, &direction);

          CAPTURE(volume, point, direction, reference_case.name, candidate.name,
                  reference_result, candidate_result);
          REQUIRE(candidate_result == reference_result);
        }
      }
    }
  }
}

// TODO - Add all of the other queries
