# =============================================================================
# Examples for how to use XDG C++ APIs
# =============================================================================

add_executable(element_volume_estimation element_volume_estimation.cpp)
target_link_libraries(element_volume_estimation PRIVATE xdg)


