name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    name: |
      libMesh=${{ matrix.libmesh }};MOAB=${{ matrix.moab }}; mfem=${{ matrix.mfem }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        libmesh: [true, false]
        moab: [true, false]
        mfem: [true, false]
        exclude:
          - moab: false
            libmesh: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y libgcc-9-dev \
                              libstdc++-9-dev \
                              libembree-dev \
                              libnetcdf-dev \
                              libhdf5-dev \
                              libeigen3-dev \
                              cmake
      - name: Update CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.24.3
          cache: true

      - name: GPRT Apt Dependencies
        shell: bash
        run: |
          sudo apt install -y \
          libpthread-stubs0-dev \
          libx11-xcb-dev \
          xorg-dev \
          libxinerama-dev \
          libglu1-mesa-dev \
          freeglut3-dev \
          mesa-common-dev \
          libglfw3

      - name: Prepare Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: MOAB Clone
        if: ${{ matrix.moab }}
        shell: bash
        run: |
          cd ~
          git clone https://bitbucket.org/fathomteam/moab.git
          cd moab
          git checkout 5.3.1

      - name: libMesh Clone
        if: ${{ matrix.libmesh }}
        shell: bash
        run: |
          cd ~
          git clone https://github.com/libMesh/libmesh.git
          cd libmesh
          git checkout v1.7.0

      - name: mfem Clone
        if: ${{ matrix.mfem }}
        shell: bash
        run: |
          cd ~
          git clone https://github.com/mfem/mfem.git
          cd mfem
          git checkout v4.9

      - name: OpenMP Environment Variables
        run: |
          echo "OMP_NUM_THREADS=1" >> $GITHUB_ENV

      - name: MOAB Environment Variables
        if: ${{ matrix.moab }}
        run: |
          echo "MOAB_SHA"=$(cd ~/moab && git rev-parse HEAD) >> $GITHUB_ENV

      - name: libMesh Environment Variables
        if: ${{ matrix.libmesh }}
        run: |
          echo "LIBMESH_SHA"=$(cd ~/libmesh && git rev-parse HEAD) >> $GITHUB_ENV
          # Enforce that we're using the debug build of libMesh
          echo "METHOD=dbg" >> $GITHUB_ENV

      - name: mfem Environment Variables
        if: ${{ matrix.mfem }}
        run: |
          echo "MFEM_SHA"=$(cd ~/mfem && git rev-parse HEAD) >> $GITHUB_ENV

      - name: MOAB Cache
        if: ${{ matrix.moab }}
        id: moab-cache
        uses: actions/cache@v3
        env:
          cache-name: moab-cache
        with:
          path: ~/MOAB
          key: moab-${{ runner.os }}-${{ env.cache-name }}-${{ env.MOAB_SHA }}

      - name: libMesh Cache
        if: ${{ matrix.libmesh }}
        id: libmesh-cache
        uses: actions/cache@v3
        env:
          cache-name: libmesh-cache
        with:
          path: ~/LIBMESH
          key: libmesh-${{ runner.os }}-${{ env.cache-name }}-${{ env.LIBMESH_SHA }}

      - name: mfem Cache
        if: ${{ matrix.mfem }}
        id: mfem-cache
        uses: actions/cache@v3
        env:
          cache-name: mfem-cache
        with:
          path: ~/mfem
          key: mfem-${{ runner.os }}-${{ env.cache-name }}-${{ env.LIBMESH_SHA }}

      - if: ${{ matrix.moab && steps.moab-cache.outputs.cache-hit != 'true' }}
        name: Build MOAB
        run: |
          cd ~/moab
          mkdir build
          cd build
          cmake -DENABLE_HDF5=ON -DENABLE_BLASLAPACK=OFF -DCMAKE_INSTALL_PREFIX=$HOME/MOAB -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          make install

      - if: ${{ matrix.libmesh && steps.libmesh-cache.outputs.cache-hit != 'true' }}
        name: Build libMesh
        shell: bash
        run: |
          cd ~
          cd libmesh
          git checkout v1.7.0
          git submodule update --init --recursive
          mkdir build
          cd build
          ../configure --prefix=$HOME/LIBMESH --enable-exodus --disable-netcdf4 --disable-eigen --disable-lapack --disable-mpi --disable-metaphysicl
          make -j4
          sudo make install

      - if: ${{ matrix.mfem && steps.mfem-cache.outputs.cache-hit != 'true' }}
        name: Build mfem
        shell: bash
        run: |
          # first let's get netcdf
          sudo apt-get update
          sudo apt-get install -y libnetcdf-dev libhdf5-dev
          cd ~
          cd mfem
          git checkout v4.9
          mkdir build
          cd build
          # manually entering the hdf5 dir since cmake can't find it on its own
          cmake .. -DMFEM_USE_HYPRE=OFF -DMFEM_USE_NETCDF=ON -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DHDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial -DBUILD_SHARED_LIBS=ON  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          make -j4
          sudo make install

      - name: Build
        shell: bash
        run: |
          export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
          mkdir build
          cd build
          CMAKE_PREFIX_PATH=""
          if [ "${{ matrix.libmesh }}" = 'true' ]; then
            CMAKE_PREFIX_PATH="$HOME/LIBMESH"
          fi
          if [ "${{ matrix.moab }}" = 'true' ]; then
            if [ -n "$CMAKE_PREFIX_PATH" ]; then
              CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;"
            fi
            CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}$HOME/MOAB"
          fi
          if [ "${{ matrix.mfem }}" = 'true' ]; then
            if [ -n "$CMAKE_PREFIX_PATH" ]; then
              CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH;"
            fi
            CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}$HOME/mfem/install"
          fi          
          cmake .. -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" -DCMAKE_INSTALL_PREFIX=$HOME/opt -DXDG_ENABLE_MOAB=${{ matrix.moab && 'ON' || 'OFF' }} -DXDG_ENABLE_LIBMESH=${{ matrix.libmesh && 'ON' || 'OFF' }} -DXDG_ENABLE_MFEM=${{ matrix.mfem && 'ON' || 'OFF' }}
          make -j4 install

      - name: Test
        shell: bash
        run: |
          cd build
          ctest -j4 --output-on-failure

      - name: Check installed executables
        shell: bash
        run: |
          ~/opt/bin/tools/find-volume

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
